# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/OneDrive/Documents/Vivado/DA/DA.srcs/sources_1/ip/SR_16bit/SR_16bit.xci
# IP: The module: 'SR_16bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/OneDrive/Documents/Vivado/DA/DA.srcs/sources_1/ip/SR_16bit/SR_16bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SR_16bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/OneDrive/Documents/Vivado/DA/DA.srcs/sources_1/ip/SR_16bit/SR_16bit.xci
# IP: The module: 'SR_16bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/OneDrive/Documents/Vivado/DA/DA.srcs/sources_1/ip/SR_16bit/SR_16bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SR_16bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
