# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.runs/adder_DA_synth_1/adder_DA.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "adder_DA_synth_1" START { ROLLUP_AUTO }
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.cache/wt [current_project]
set_property parent.project_path E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/Kuro/AppData/Roaming/Xilinx/Vivado/2019.2/xhub/board_store} [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
set_property ip_output_repo e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_ip -quiet e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA.xci

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
OPTRACE "Configure IP Cache" START { }

set cached_ip [config_ip_cache -export -no_bom  -dir E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.runs/adder_DA_synth_1 -new_name adder_DA -ip [get_ips adder_DA]]

OPTRACE "Configure IP Cache" END { }
if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top adder_DA -part xc7a100tcsg324-1 -mode out_of_context
OPTRACE "synth_design" END { }
OPTRACE "Write IP Cache" START { }

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix adder_DA_ adder_DA.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ adder_DA_stub.v
 lappend ipCachedFiles adder_DA_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ adder_DA_stub.vhdl
 lappend ipCachedFiles adder_DA_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ adder_DA_sim_netlist.v
 lappend ipCachedFiles adder_DA_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ adder_DA_sim_netlist.vhdl
 lappend ipCachedFiles adder_DA_sim_netlist.vhdl
 set TIME_taken [expr [clock seconds] - $TIME_start]

 if { [get_msg_config -count -severity {CRITICAL WARNING}] == 0 } {
  config_ip_cache -add -dcp adder_DA.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips adder_DA]
 }
OPTRACE "Write IP Cache" END { }
}

rename_ref -prefix_all adder_DA_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef adder_DA.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "adder_DA_synth_1_synth_report_utilization_0" "report_utilization -file adder_DA_utilization_synth.rpt -pb adder_DA_utilization_synth.pb"
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.runs/adder_DA_synth_1/adder_DA.dcp e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.runs/adder_DA_synth_1/adder_DA.dcp e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.runs/adder_DA_synth_1/adder_DA_stub.v e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.runs/adder_DA_synth_1/adder_DA_stub.vhdl e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.runs/adder_DA_synth_1/adder_DA_sim_netlist.v e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.runs/adder_DA_synth_1/adder_DA_sim_netlist.vhdl e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.ip_user_files/ip/adder_DA]} {
  catch { 
    file copy -force e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA_stub.v E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.ip_user_files/ip/adder_DA
  }
}

if {[file isdir E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.ip_user_files/ip/adder_DA]} {
  catch { 
    file copy -force e:/OneDrive/Documents/Vivado/SIGNED/DA/DA.srcs/sources_1/ip/adder_DA/adder_DA_stub.vhdl E:/OneDrive/Documents/Vivado/SIGNED/DA/DA.ip_user_files/ip/adder_DA
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "adder_DA_synth_1" END { }
